Controllers/DoctorsController.cs
using System;
using System.IO;
using ClinicaVeterinaria.Models;
using Microsoft.Ajax.Utilities;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;
using System.Drawing;

namespace ClinicaVeterinaria.Controllers
{
    // inizio codice MG
    public class DoctorsController : Controller
    {
        private DBContext db = new DBContext();


        [HttpGet]
        public ActionResult Index(string search)
        {
            var beasts = db.Beasts
                   .OrderByDescending(b => b.BeastID) 
                   .ToList();

            if (!string.IsNullOrEmpty(search))
            {
                beasts = beasts.Where(b => b.Nome.Contains(search) || b.MicrochipCodice == search).ToList();
            }

            ViewBag.SearchString = search;
            ViewBag.NoResults = beasts.Count == 0;
            return View(beasts);
        }
        [HttpGet]
        public ActionResult AddBeast()
        {
            return View();
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddBeast(Beast beast, HttpPostedFileBase Foto)
        {
            if (beast.DataRegistrazione < beast.DataNascita)
            {
                TempData["MessageDate"] = "la data di nascita non può essere posteriore alla data di registrazione";
                return View(beast);
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (Foto != null && Foto.ContentLength > 0)
                    {
                        string fileName = Path.GetFileName(Foto.FileName);
                        string path = Path.Combine(Server.MapPath("~/assets/img/"), fileName);
                        Foto.SaveAs(path);
                        beast.Foto = "/assets/img/" + fileName;
                    }

                    db.Beasts.Add(beast);
                    db.SaveChanges();
                    return RedirectToAction("Details", new { id = beast.BeastID });
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Impossibile aggiungere la bestia. Si è verificato un errore: " + ex.Message);
                }
            }

            return View(beast);
        }

        //Fine Codice Pes


        // GET: Doctors
        // CODICE MARCO SILVERI

        [HttpGet]
        public ActionResult AddExamination(int id)
        {
            var beast = db.Beasts.FirstOrDefault(x => x.BeastID == id);
            if (beast == null)
            {
                return HttpNotFound();
            }

            ViewBag.Bestia = beast;
            return View();
        }



        [HttpGet]
        public ActionResult AddHospitalization(int id)
        {
            var beast = db.Beasts.FirstOrDefault(x => x.BeastID == id);
            ViewBag.Bestia = beast;
            var tuoModello = new Hospitalization();
            tuoModello.DataInizioRicovero = tuoModello.DataInizioRicovero.Date != DateTime.MinValue.Date ? tuoModello.DataInizioRicovero : DateTime.Now;

            return View(tuoModello);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddExamination([Bind(Include = "ExaminationID, DataVisita, PatologieRiscontrate, NumeroRicetta, Ricetta, Prezzo, DoctorID, BeastID")]  Examination esame)
        {

            

            var beast = db.Beasts.SingleOrDefault(b => b.BeastID == esame.BeastID);

            if (beast != null)
            {

                if (beast.DataRegistrazione > esame.DataVisita)
                {
                    TempData["MessageReg"] = "La data di registrazione non può essere successiva alla data della visita.";
                    return View(esame);
                }
            }

            if (esame.DoctorID <= 0)
            {
                ModelState.AddModelError("DoctorID", "La selezione del dottore è obbligatoria.");
            }
            if (esame.BeastID <= 0)
            {
                ModelState.AddModelError("BeastID", "La selezione dell'animale è obbligatoria.");
            }

            if (ModelState.IsValid)
            {
                db.Examinations.Add(esame);
                db.SaveChanges();
                TempData["message"] = "Esame prenotato con successo";
                return RedirectToAction("Details", new { id = esame.BeastID });
            }
            else
            {
                TempData["messageError"] = "Errore nella compilazione dell'esame";
            }

            return View(esame);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var beast = db.Beasts
                           .Include(b => b.Examinations) 
                           .Include(b => b.Hospitalizations) 
                           .FirstOrDefault(b => b.BeastID == id);

            if (beast == null)
            {
                return HttpNotFound();
            }

            return View(beast);
        }

        public ActionResult DottoreDet(int? id)
        {
            if ( id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var dottore = db.Doctors.FirstOrDefault(d => d.DoctorID == id);
            if ( dottore == null)
            {
                return HttpNotFound();
            }

            return View(dottore);
        }

        [HttpPost]
        public ActionResult AddHospitalization(Hospitalization hospitalization)
        {
            try
            {
                ViewBag.DoctorList = new SelectList(db.Doctors.ToList(), "DoctorID", "Nome");
                ViewBag.BeastList = new SelectList(db.Beasts.ToList(), "BeastID", "Nome");

                var beast = db.Beasts.SingleOrDefault(b => b.BeastID == hospitalization.BeastID);

                if (beast != null)
                {
                    if (beast.DataRegistrazione > hospitalization.DataInizioRicovero)
                    {
                        TempData["MessageOsp"] = "La data di registrazione non può essere successiva all'inizio del ricovero.";
                        return View(hospitalization);
                    }
                }

                if (hospitalization.DoctorID <= 0)
                {
                    ModelState.AddModelError("DoctorID", "La selezione del dottore è obbligatoria.");
                }
                if (hospitalization.BeastID <= 0)
                {
                    ModelState.AddModelError("BeastID", "La selezione della Bestia è obbligatoria.");
                }
                if (ModelState.IsValid)
                {
                    db.Hospitalizations.Add(hospitalization);
                    db.SaveChanges();
                    TempData["message"] = "Ricovero creato con succcesso!";
                    return RedirectToAction("Details", new { id = hospitalization.BeastID });
                }
                else
                {
                    TempData["messageError"] = "Errore nella compilazione del ricovero!";
                }
                return View(hospitalization);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"Si è verificato un errore durante la creazione del ricovero: {ex.Message}");
            }
            return View(hospitalization);
        }

        public ActionResult ActiveHospitalizations()
        {
            DateTime currentDate = DateTime.Now;

            var allHospitalizations = db.Hospitalizations.ToList();
            return View(allHospitalizations);
        }
        public ActionResult GetHospitalizationDetails(int id)
        {
            var hospitalization = db.Hospitalizations.Find(id);
            if (hospitalization != null)
            {
                var details = new
                {
                    animalName = hospitalization.Beast.Nome,
                    doctorName = hospitalization.Doctor.Nome + " " + hospitalization.Doctor.Cognome,
                    prognosis = hospitalization.Prognosi,
                    dailyCost = hospitalization.CostoGiornalieroRicovero
                };
                return Json(details, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return HttpNotFound();
            }
        }

        [HttpPost]
        public ActionResult CheckoutHospitalization(int id)
        {
            var hospitalization = db.Hospitalizations.Find(id);
            if (hospitalization != null)
            {
                hospitalization.DataFineRicovero = DateTime.Now.Date;
                db.SaveChanges();
                return Json(new { success = true });
            }
            else
            {
                return HttpNotFound();
            }
        }

        [HttpPost]
        public async Task<ActionResult> ContabilizzazioneRicoveriAsincrona()
        {
            try
            {
                var activeHospitalizations = await db.Hospitalizations
                    .Where(h => h.DataFineRicovero == null && h.Beast.Microchip)
                    .Select(h => new
                    {
                        AnimalName = h.Beast.Nome,
                        StartDate = h.DataInizioRicovero
                    })
                    .ToListAsync();

                return Json(activeHospitalizations, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { error = ex.Message });
            }
        }

        // Fine codice MG
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Applicazione ASP.NET</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-7hUpOZrHbH6gj3JTG/As/SRTIDg4C3kZy3nDMeXNbOgNtqCL3KL9XDeIJmdHR8yYj5h2K3O/BZWl7EFKte9DEw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @{
        var currentUrl = Request.Url.AbsolutePath.ToLower();
        var folder = currentUrl.Split('/')[1];
    }

    @if (folder == "doctors")
    {
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-success d-print-none">
            <div class="container">
                
                <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Attiva/Disattiva spostamento" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <img src="https://media.istockphoto.com/id/1470993851/it/vettoriale/animale-amore-simbolo-zampa-stampa-con-cuore-vettore-isolato.jpg?s=612x612&w=0&k=20&c=qMAqAOfgsyqI2d-eVS3ARyTCdkIYkNoOI-Vf9WvnQzU=" width="40px" height="40px" class="rounded rounded-5 me-3"/>
                        @Html.ActionLink("ClinicaPerBestie", "Index", "Doctors", new { area = "" }, new { @class = "navbar-brand" })
                        <li>
                            <a href="@Url.Action("Index", "Doctors", new { area = "" })" class="nav-link">
                                <i class="bi bi-heart-pulse"></i> Bestie
                            </a>
                        </li>

                        <li>
                            <a href="@Url.Action("ActiveHospitalizations", "Doctors", new { area = "" })" class="nav-link">
                                <i class="bi bi-clipboard2-pulse"></i> Ricoveri Attivi
                            </a>
                        </li>

                    </ul>
                </div>
                @if (Session["UserM"] != null)
                {
                    <a class="me-5 welcome-btn" href="/Doctors/DottoreDet?id=@Session["DoctorID"]" style="color: inherit; text-decoration: none;"><i class="bi bi-person-circle"></i> Benvenuto, @Session["UserM"] </a>
                }
                else if (Session["UserF"] != null)
                {
                    <a class="me-5 welcome-btn" href="/Pharmacists/FarmacistaDet?id=@Session["PharmacistID"]" style="color: inherit; text-decoration: none;">Benvenuto, @Session["UserF"]</a>//TODO
                }
                @if (Request.Cookies[".ASPXAUTH"] != null)
                {
                    <form action="@Url.Action("LogoutFarmacia", "Home")" method="post">
                        @Html.AntiForgeryToken()
                        <button type="submit" style="background-color: #1c6345" class="btn btn-success">Logout <i class="bi bi-box-arrow-in-right"></i></button>
                    </form>
                }
            </div>
        </nav>
    }
    else if (folder == "pharmacists")
    {
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark d-print-none" style="background-color:darkcyan">
            <div class="container">
                <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Attiva/Disattiva spostamento" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <img src="https://media.istockphoto.com/id/1470993851/it/vettoriale/animale-amore-simbolo-zampa-stampa-con-cuore-vettore-isolato.jpg?s=612x612&w=0&k=20&c=qMAqAOfgsyqI2d-eVS3ARyTCdkIYkNoOI-Vf9WvnQzU=" width="40px" height="40px" class="rounded rounded-5 me-3" />
                        @Html.ActionLink("FarmaciaPerBestie", "Index", "Pharmacists", new { area = "" }, new { @class = "navbar-brand" })
                        <li>
                            <a href="@Url.Action("Index", "Pharmacists", new { area = "" })" class="nav-link">
                                <i class="bi bi-capsule"></i> Prodotti
                            </a>
                        </li>

                        <li>
                            <a href="@Url.Action("Orders", "Pharmacists", new { area = "" })" class="nav-link">
                                <i class="bi bi-bag-check"></i> Ordini
                            </a>
                        </li>

                        <li>@Html.ActionLink("Medicina per Data", "MedicinaXData", "Pharmacists", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Medicina per Cliente", "MedicinaXCliente", "Pharmacists", new { area = "" }, new { @class = "nav-link" })</li>
                    </ul>
                </div>
                @if (Session["UserM"] != null)
                {
                    <a class="me-5 welcome-btn" href="/Doctors/DottoreDet?id=@Session["DoctorID"]" style="color: inherit; text-decoration: none;">Benvenuto, @Session["UserM"]</a>
                }
                else if (Session["UserF"] != null)
                {
                    <a class="me-5 welcome-btn" href="/Pharmacists/FarmacistaDet?id=@Session["PharmacistID"]" style="color: inherit; text-decoration: none;"><i class="bi bi-person-circle"></i> Benvenuto, @Session["UserF"]</a>//TODO
                }
                @if (Request.Cookies[".ASPXAUTH"] != null)
                {
                    <form action="@Url.Action("LogoutFarmacia", "Home")" method="post">
                        @Html.AntiForgeryToken()
                        <button type="submit"  style="background-color: #04414a"  class="btn btn-primary">Logout <i class="bi bi-box-arrow-in-right"></i> </button>
                    </form>
                }
            </div>
        </nav>
    }
    else
    {
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-success d-print-none">
            <div class="container">
                <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Attiva/Disattiva spostamento" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @Html.ActionLink("PortalePerBestie", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                        <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    </ul>
                </div>                
            </div>
        </nav>
    }

    <div class="container body-content">
        @RenderBody()
        @if (folder == "doctors")
        {
            <footer class="mt-4 border-top border-success">
                <p class="text-success mt-2">&copy; @DateTime.Now.Year - ClinicaPerBestie.</p>
            </footer>
        }
        else if (folder == "pharmacists")
        {
            <footer class="mt-4" style="border-top:1px solid; border-color:darkcyan" >
                <p class="mt-2" style="color:darkcyan">&copy; @DateTime.Now.Year - FarmaciaPerBestie.</p>
            </footer>
        }
        else
        {
            <footer class="mt-4 border-top border-success">
                <p class="text-success mt-2">&copy; @DateTime.Now.Year - PortalePerBestie.</p>
            </footer>
        }

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>