Models/CheckoutSummaryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ClinicaVeterinaria.Models
{
    public class CheckoutSummaryViewModel
    {
        public Beast Animale { get; set; }
        public List<Sale> Vendite { get; set; }
        public decimal PrezzoTotale { get; set; }
        public string NumeroRicetta { get; set; }
        public DateTime DataVendita { get; set; }
        public int Quantita { get; set; }
        public int PharmacistID { get; set; }
        public string NomeFarmacista { get; set; }
    }
}

Models/Pharmacist.cs
namespace ClinicaVeterinaria.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Pharmacist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pharmacist()
        {
            Sales = new HashSet<Sale>();
        }

        public int PharmacistID { get; set; }

        [Required]
        [StringLength(50)]
        public string Nome { get; set; }

        [Required]
        [StringLength(50)]
        public string Cognome { get; set; }

        [Column(TypeName = "date")]
        public DateTime DataNascita { get; set; }

        [Required]
        [StringLength(100)]
        public string LuogoNascita { get; set; }

        [Required]
        [StringLength(100)]
        public string LuogoResidenza { get; set; }

        [Required]
        [StringLength(16)]
        public string CodiceFiscale { get; set; }

        [Required]
        [StringLength(5)]
        public string Matricola { get; set; }

        [Required]
        [StringLength(255)]
        public string Email { get; set; }

        [Required]
        [StringLength(50)]
        public string PasswordFarmacista { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
    }
}

Controllers/PharmacistsController.cs
using ClinicaVeterinaria.Models;
using System.Linq;
using System.Web.Mvc;
using System.Data.Entity;
using System.Collections.Generic;
using System;
using System.Net;

namespace ClinicaVeterinaria.Controllers
{
    public class PharmacistsController : Controller
    {
        private DBContext db = new DBContext();


        public ActionResult Index(string search, string descriptionSearch)
        {
            var redirect = RedirectToLoginIfNotAuthenticated();
            if (redirect != null) return redirect;
            IQueryable<Product> products = db.Products;

            if (!string.IsNullOrEmpty(search))
            {
                products = products.Where(p => p.Nome.Contains(search));
                return View(products.ToList());
            }

            if (!string.IsNullOrEmpty(descriptionSearch))
            {
                products = products.Where(p => p.Descrizione.Contains(descriptionSearch));
                return View(products.ToList());
            }

            return View(products.ToList());
        }


        public ActionResult Details(int id)
        {
            var redirect = RedirectToLoginIfNotAuthenticated();
            if (redirect != null) return redirect;
            var product = db.Products
                            .Include(p => p.Drawer)
                            .Include(p => p.Drawer.Locker)
                            .FirstOrDefault(p => p.ProductID == id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        public ActionResult AddToReport(int id)
        {
            var redirect = RedirectToLoginIfNotAuthenticated();
            if (redirect != null) return redirect;
            var product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }

            List<int> reportProducts = Session["ReportProducts"] as List<int>;
            if (reportProducts == null)
            {
                reportProducts = new List<int>();
            }

            reportProducts.Add(id);
            Session["ReportProducts"] = reportProducts;

            return RedirectToAction("Index");
        }

        public ActionResult Orders()
        {
            var redirect = RedirectToLoginIfNotAuthenticated();
            if (redirect != null) return redirect;
            List<int> reportProductID = Session["ReportProducts"] as List<int>;
            List<Product> reportProducts = new List<Product>();
            decimal totalPrice = 0;

            if (reportProductID != null)
            {
                foreach (int productId in reportProductID)
                {
                    var product = db.Products.Find(productId);
                    if (product != null)
                    {
                        reportProducts.Add(product);
                        totalPrice += product.Prezzo;
                    }
                }
            }

            ViewBag.TotalPrice = totalPrice;

            var pharmacists = db.Pharmacists.Select(p => new
            {
                PharmacistID = p.PharmacistID,
                Name = p.Nome
            }).ToList();

            ViewBag.Pharmacists = new SelectList(pharmacists, "PharmacistID", "Name");

            return View(reportProducts);
        }


        public ActionResult RemoveFromReport(int id)
        {
            var redirect = RedirectToLoginIfNotAuthenticated();
            if (redirect != null) return redirect;
            List<int> reportProducts = Session["ReportProducts"] as List<int>;
            if (reportProducts != null)
            {
                reportProducts.Remove(id);
                Session["ReportProducts"] = reportProducts;
            }

            return RedirectToAction("Orders");
        }

        [HttpPost]
        public ActionResult Checkout(string codiceFiscale, string numeroRicetta, int pharmacistId, DateTime dataVendita)
        {
            var redirect = RedirectToLoginIfNotAuthenticated();
            if (redirect != null) return redirect;
            if (codiceFiscale.Length != 16)
            {
                TempData["ErrorMessage"] = "Il codice fiscale deve essere lungo 16 caratteri.";
                return RedirectToAction("Orders");
            }

            var animal = db.Beasts.FirstOrDefault(b => b.CodiceFiscale == codiceFiscale);
            if (animal == null)
            {
                TempData["ErrorMessage"] = "Il codice fiscale inserito non è associato a nessun animale.";
                return RedirectToAction("Orders");
            }

            List<int> reportProductIDs = Session["ReportProducts"] as List<int>;
            if (reportProductIDs != null && reportProductIDs.Count > 0)
            {
                foreach (int productId in reportProductIDs)
                {
                    var product = db.Products.Find(productId);
                    if (product != null)
                    {
                        var sale = new Sale
                        {
                            ProductID = productId,
                            CodiceFiscale = codiceFiscale,
                            NumeroRicetta = numeroRicetta,
                            DataVendita = dataVendita,
                            Prezzo = product.Prezzo,
                            PharmacistID = pharmacistId
                        };
                        db.Sales.Add(sale);
                    }
                }
                db.SaveChanges();

                var pharmacist = db.Pharmacists.FirstOrDefault(p => p.PharmacistID == pharmacistId);
                string nomeFarmacista = pharmacist != null ? pharmacist.Nome : "Nome non trovato";


                var summaryViewModel = new CheckoutSummaryViewModel
                {
                    NumeroRicetta = numeroRicetta,
                    NomeFarmacista = nomeFarmacista,
                    DataVendita = dataVendita
                };

                Session["ReportProducts"] = null;

                TempData["SuccessMessage"] = "Checkout completato con successo.";
                return RedirectToAction("CheckoutSummary", new { codiceFiscale = codiceFiscale, numeroRicetta = numeroRicetta, pharmacistId = pharmacistId, dataVendita = dataVendita });
            }
            else
            {
                TempData["ErrorMessage"] = "Nessun prodotto nel resoconto.";
                return RedirectToAction("Orders");
            }
        }


        public ActionResult CheckoutSummary(string codiceFiscale, string numeroRicetta, int pharmacistId, DateTime dataVendita)
        {
            var redirect = RedirectToLoginIfNotAuthenticated();
            if (redirect != null) return redirect;
            var summaryViewModel = new CheckoutSummaryViewModel();

            summaryViewModel.Animale = db.Beasts.FirstOrDefault(b => b.CodiceFiscale == codiceFiscale);

            var oggi = DateTime.Today;

            summaryViewModel.Vendite = db.Sales
                            .Where(s => s.CodiceFiscale == codiceFiscale &&
                                        s.DataVendita.Year == oggi.Year &&
                                        s.DataVendita.Month == oggi.Month &&
                                        s.DataVendita.Day == oggi.Day)
                            .OrderByDescending(s => s.DataVendita)
                            .ToList();

            summaryViewModel.PrezzoTotale = summaryViewModel.Vendite.Sum(v => v.Prezzo);
            summaryViewModel.DataVendita = dataVendita;
            summaryViewModel.NumeroRicetta = numeroRicetta;
            summaryViewModel.PharmacistID = pharmacistId;
            var pharmacist = db.Pharmacists.FirstOrDefault(p => p.PharmacistID == pharmacistId);
            summaryViewModel.NomeFarmacista = pharmacist != null ? pharmacist.Nome : "Nome non trovato";

            return View(summaryViewModel);
        }


        public ActionResult AddNewProduct()
        {
            var redirect = RedirectToLoginIfNotAuthenticated();
            if (redirect != null) return redirect;
            ViewBag.SupplierID = new SelectList(db.Suppliers, "SupplierID", "NomeAzienda");
            ViewBag.DrawerID = new SelectList(db.Drawers, "DrawerID", "DrawerID");
            return View();
        }

        public ActionResult MedicinaXCliente()
        {

            var redirect = RedirectToLoginIfNotAuthenticated();
            if (redirect != null) return redirect;

            var proprietari = db.Beasts.Select(b => new
            {
                NomeProprietario = b.Proprietario,
                CodiceFiscale = b.CodiceFiscale
            }).Distinct().ToList();

            ViewBag.Proprietari = new SelectList(proprietari, "CodiceFiscale", "NomeProprietario");

            return View();
        }
        public ActionResult GetProdottiByCodiceFiscale(string codiceFiscale)
        {
            var redirect = RedirectToLoginIfNotAuthenticated();
            if (redirect != null) return redirect;
            var vendite = db.Sales
                            .Where(s => s.CodiceFiscale == codiceFiscale)
                            .Select(s => s.ProductID)
                            .Distinct()
                            .ToList();

            if (!vendite.Any())
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.NotFound, "Nessuna vendita registrata per il codice fiscale inserito.");
            }

            var prodotti = db.Products
                             .Where(p => vendite.Contains(p.ProductID))
                             .ToList();

            return PartialView("_ProdottiByCodiceFiscale", prodotti);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddNewProduct([Bind(Include = "ProductID,Nome,Descrizione,SupplierID,DrawerID,Prezzo")] Product product)
        {

Views/Pharmacists/AddNewProduct.cshtml
@model ClinicaVeterinaria.Models.Product

@{
    ViewBag.Title = "Aggiungi Farmaco";
}

<h2>Aggiungi Farmaco</h2>

@using (Html.BeginForm("AddNewProduct", "Pharmacists", FormMethod.Post, new { @class = "needs-validation", novalidate = "novalidate" }))
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                <div class="invalid-feedback">Il nome del farmaco è obbligatorio.</div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Descrizione, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Descrizione, new { htmlAttributes = new { @class = "form-control" } })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Prezzo, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.Prezzo, new { htmlAttributes = new { @class = "form-control", type = "number", step = "1.00", min = "1" } })
            </div>
        </div>

        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.SupplierID, "Fornitore", htmlAttributes: new { @class = "control-label" })
                @Html.DropDownList("SupplierID", null, "Seleziona un fornitore", new { @class = "form-control", required = "required" })
                <div class="invalid-feedback">Si prega di selezionare un fornitore.</div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DrawerID, "Cassetto", htmlAttributes: new { @class = "control-label" })
                @Html.DropDownList("DrawerID", null, "Seleziona un cassetto", new { @class = "form-control", required = "required" })
                <div class="invalid-feedback">Si prega di selezionare un cassetto.</div>
            </div>
        </div>
    </div>

    <button type="submit" class="btn btn-primary">Aggiungi</button>
}

Views/Pharmacists/CheckoutSummary.cshtml
@model ClinicaVeterinaria.Models.CheckoutSummaryViewModel

<h2 class="pb-3" style="color:darkcyan; border-bottom:1px solid">Riepilogo prodotti comprati</h2>
<h3 class="mb-2" style="color:darkcyan;">Informazioni sull'animale e Proprietario</h3>
<p class="fs-5">Nome Animale: @Model.Animale.Nome</p>
<p class="fs-5">Nome Proprietario: @Model.Animale.Proprietario</p>
<p class="fs-5">Codice Fiscale: @Model.Animale.CodiceFiscale</p>
<p class="fs-5">Numero Ricetta: @Model.NumeroRicetta</p>
<p class="fs-5">Nome Farmacista: @Model.NomeFarmacista</p>

<h3 class="pb-3" style="color:darkcyan; border-bottom:1px solid">Prodotti Venduti</h3>
<div class="d-flex justify-content-between mt-4">
    <h4>Totale Guadagnato: @String.Format("{0:C}", Model.PrezzoTotale)</h4>
    <button id="printButton" class="btn text-white d-print-none" style="background-color:darkcyan">Stampa PDF</button>
</div>
<table class="table">
    <thead>
        <tr>
            <th>Prodotto</th>
            <th>Venduto il</th>
            <th>Prezzo</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var vendita in Model.Vendite)
        {
            <tr>
                <td>@vendita.Product.Nome</td>
                <td>@vendita.DataVendita.ToString("dd/MM/yyyy")</td>
                <td>@String.Format("{0:C}", vendita.Prezzo)</td>
            </tr>
        }
    </tbody>
</table>

<script>
    document.getElementById('printButton').addEventListener('click', function () {
        window.print();
    });
</script>

Views/Pharmacists/Details.cshtml
@model ClinicaVeterinaria.Models.Product

@{
    ViewBag.Title = "Dettagli Prodotto";
}

    <h2 class="pb-3" style="color:darkcyan; border-bottom:1px solid; border-color:darkcyan">Dettagli Prodotto</h2>

    <dl class="d-flex mt-3 mb-4">
        <div class="me-3">
            <dt>Armadietto</dt>
            <dd>@Html.DisplayFor(model => model.Drawer.Locker.Descrizione)</dd>

            <dt>Numero Cassetto</dt>
            <dd>@Html.DisplayFor(model => model.Drawer.DrawerID)</dd>
        </div>
        <div class="ms-3">
            <dt>Nome</dt>
            <dd>@Html.DisplayFor(model => model.Nome)</dd>

            <dt>Descrizione</dt>
            <dd>@Html.DisplayFor(model => model.Descrizione)</dd>
        </div>
    </dl>

    <p>
        @Html.ActionLink("Aggiungi al resoconto", "AddToReport", new { id = Model.ProductID }, new { @class = "btn btn-success me-2", style = "background-color: darkcyan;" })
        @Html.ActionLink("Torna alla lista", "Index", null, new { @class = "btn btn-secondary ms-2" })
    </p>

Views/Pharmacists/FarmacistaDet.cshtml
@model ClinicaVeterinaria.Models.Pharmacist

<style>
    body {
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        background-color: #f8f9fa;
    }

    .card {
        border-radius: 15px;
        border: none;
        box-shadow: 0 4px 8px rgba(0,0,0,0.1);
        transition: transform 0.3s ease-in-out;
    }

        .card:hover {
            transform: translateY(-5px);
            box-shadow: 0 6px 12px rgba(0,0,0,0.15);
        }

    .card-title {
        font-weight: 600;
        color: #007bff;
    }

    dt {
        font-size: 0.9em;
        color: #6c757d;
    }

    dd {
        font-size: 1.1em;
    }

    .card-body {
        padding: 2rem;
    }
</style>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-6 mb-5 mt-4">
            <div class="card shadow-lg">
                <div class="card-header p-3 text-white" style="background-color:darkcyan">
                    <h3 class="mb-0 mx-2">Dettagli Farmacista</h3>
                </div>
                <div class="card-body py-3 px-4">
                    <h3 class="card-title mb-4" style="color:darkcyan">@Model.Nome @Model.Cognome</h3>
                    <dl class="row">
                        <dt class="col-sm-5">Data di Nascita</dt>
                        <dd class="col-sm-7">@Model.DataNascita.ToShortDateString()</dd>

                        <dt class="col-sm-5">Luogo di Nascita</dt>
                        <dd class="col-sm-7">@Model.LuogoNascita</dd>

                        <dt class="col-sm-5">Luogo di Residenza</dt>
                        <dd class="col-sm-7">@Model.LuogoResidenza</dd>

                        <dt class="col-sm-5">Codice Fiscale</dt>
                        <dd class="col-sm-7">@Model.CodiceFiscale</dd>

                        <dt class="col-sm-5">Matricola</dt>
                        <dd class="col-sm-7">@Model.Matricola</dd>

                        <dt class="col-sm-5">Email</dt>
                        <dd class="col-sm-7">@Model.Email</dd>

                        <dt class="col-sm-5">Password</dt>
                        <dd class="col-sm-7">@Model.PasswordFarmacista</dd>
                    </dl>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Pharmacists/Index.cshtml
@model IEnumerable<ClinicaVeterinaria.Models.Product>

@{
    ViewBag.Title = "Cerca Prodotti";
}
<h2 class=" pb-3" style="color:darkcyan;border-bottom:1px solid; border-color:darkcyan">Pagina Prodotti</h2>
<h3 style="color:darkcyan">Cerca Prodotti</h3>
<div class="d-flex justify-content-between align-content-center my-3">
    @using (Html.BeginForm("Index", "Pharmacists", FormMethod.Get, new { @class = "form-inline" }))
    {
        <div class="d-flex align-items-center">
            <div class="input-group m-0">
                @Html.TextBox("search", null, new { @class = "form-control", @placeholder = "Nome Prodotto" })
                <button type="submit" class="btn text-white" style="background-color:darkcyan">Cerca</button>
            </div>

            <div class="input-group ms-4">
                @Html.TextBox("descriptionSearch", null, new { @class = "form-control", @placeholder = "Uso Prodotto" })
                <button type="submit" class="btn text-white" style="background-color:darkcyan">Cerca</button>
            </div>
        </div>
    }

<div>
    <a href="@Url.Action("Ricetta", "Pharmacists")" class="btn btn-success float-right" style="background-color:darkcyan">Ricerca Ricetta</a>
    <a href="@Url.Action("AddNewProduct", "Pharmacists")" class="btn btn-success float-right" style="background-color:darkcyan">Aggiungi Nuovo Prodotto</a>
</div>
</div>

@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success">
        @TempData["SuccessMessage"]
    </div>
}

@if (!Model.Any())
{
    <div class="alert alert-warning">Prodotto non trovato.</div>
}
else
{
    <table class="table">
        <thead>
            <tr class="align-items-center">
                <th>Nome</th>
                <th>Descrizione</th>
                <th>Prezzo</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.Nome)</td>
                    <td>@Html.DisplayFor(modelItem => item.Descrizione)</td>
                    <td>@Html.DisplayFor(modelItem => item.Prezzo)€</td>
                    <td class="d-flex justify-content-center">
                        @Html.ActionLink("Aggiungi All'ordine", "AddToReport", new { id = item.ProductID }, new { @class = "btn me-2 text-white", style = "background-color:darkcyan" })
                        @Html.ActionLink("Dettagli", "Details", new { id = item.ProductID }, new { @class = "btn ms-2 text-white", style = "background-color:#016565" })
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

Views/Pharmacists/MedicinaXCliente.cshtml
<h2 class="pb-3" style="color:darkcyan;border-bottom:1px solid; border-color:darkcyan;">Vendite per cliente</h2>
<h3 style="color:darkcyan;">Inserisci Un Codice Fiscale</h3>
<div class="container mt-3">
    <div class="row justify-content-center">
            <div class="input-group mb-3 p-0">
                <input type="text" class="form-control" style="border-color:darkcyan" id="codiceFiscaleInput" placeholder="Inserisci Codice Fiscale" aria-label="Codice Fiscale" aria-describedby="button-addon">
                <button class="btn text-white" style="background-color:darkcyan" type="button" id="btnMostraProdotti">Cerca Vendite</button>
            </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div id="prodottiContainer"></div>
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
    $(document).ready(function () {
        $('#btnMostraProdotti').click(function () {
            var codiceFiscale = $('#codiceFiscaleInput').val();
            if (codiceFiscale) {
                $.ajax({
                    url: '@Url.Action("GetProdottiByCodiceFiscale", "Pharmacists")',
                    type: 'GET',
                    data: { codiceFiscale: codiceFiscale },
                    success: function (data) {
                        $('#prodottiContainer').html(data);
                    },
                    error: function() {
                        $('#prodottiContainer').html('<div class="alert alert-danger" role="alert">Nessuna vendita registrata per il codice fiscale inserito.</div>');
                    }
                });
            } else {
                $('#prodottiContainer').empty();
            }
        });
    });
    </script>
}

Views/Pharmacists/MedicinaXData.cshtml
@{
    ViewBag.Title = "Medicina per Data";
}

<h2 class="pb-3" style="color:darkcyan; border-bottom:1px solid; border-color:darkcyan">@ViewBag.Title</h2>

<div class="form-group">
    <label for="dataVendita">Data Vendita:</label>
    <input type="date" class="form-control" style="border-color:darkcyan" id="dataVendita" name="dataVendita">
</div>
<button id="btnCercaMedicine" class="btn text-white mt-3" style="background-color:darkcyan">Cerca Medicine</button>

<div id="medicineContainer"></div>

@section Scripts {
    <script type="text/javascript">
    $(document).ready(function () {
        $('#btnCercaMedicine').click(function () {
            var dataVendita = $('#dataVendita').val();
            if (dataVendita) {
                $.ajax({
                    url: '@Url.Action("GetMedicineByDate", "Pharmacists")',
                    type: 'POST',
                    data: { dataVendita: dataVendita },
                    success: function (data) {
                        $('#medicineContainer').html(data);
                    },
                    error: function() {
                        $('#medicineContainer').html('<span style="color: red;">Nessuna medicina trovata per questa data.</span>');
                    }
                });
            } else {
                $('#medicineContainer').empty();
            }
        });
    });
    </script>
}

Views/Pharmacists/Orders.cshtml
@model IEnumerable<ClinicaVeterinaria.Models.Product>

@{
    ViewBag.Title = "Resoconto";
}


<h2 class="pb-3" style="color:darkcyan; border-bottom:solid 1px; border-color:darkcyan">Riepilogo Ordini</h2>

@if (!Model.Any())
{
    <div class="alert alert-warning">Nessun prodotto nel resoconto.</div>
}
else
{
        <table class="table">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Descrizione</th>
                    <th>Prezzo</th>
                    <th>Azioni</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.Nome)</td>
                        <td>@Html.DisplayFor(modelItem => item.Descrizione)</td>
                        <td>@Html.DisplayFor(modelItem => item.Prezzo)€</td>
                        <td>
                            @Html.ActionLink("Rimuovi", "RemoveFromReport", new { id = item.ProductID }, new { @class = "btn btn-danger" })
                        </td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <th>Totale:</th>
                    <th></th>
                    <th>@ViewBag.TotalPrice €</th>
                    <th></th>
                </tr>
            </tfoot>
        </table>
}
@using (Html.BeginForm("Checkout", "Pharmacists", FormMethod.Post, new { @class = "container mt-5" }))
{
    if (TempData["ErrorMessage"] != null)
    {
        <div class="alert alert-danger">
            @TempData["ErrorMessage"]
        </div>
    }
<div class="d-flex">
    <div class="me-3">
        <div class="form-group">
            <label for="codiceFiscale">Codice Fiscale:</label>
            <input type="text" id="codiceFiscale" name="codiceFiscale" style="border-color:darkcyan" class="form-control" required />
        </div>
        <div class="form-group">
            <label for="numeroRicetta">Numero Ricetta:</label>
            <input type="number" id="numeroRicetta" name="numeroRicetta" style="border-color:darkcyan" class="form-control" required min="1" />
        </div>
    </div>
    <div class="ms-3">
        <div class="form-group">
            <label for="dataVendita">Data Vendita:</label>
            <input type="date" id="dataVendita" name="dataVendita" value="@DateTime.Today.ToString("yyyy-MM-dd")" style="border-color:darkcyan" class="form-control" readonly required />
        </div>

        @Html.Hidden("PharmacistID", (int)Session["PharmacistID"])
        <div class="mt-3">
            @Html.Label("NomeDottore", "Dottore", new { @class = "form-label" })
            @Html.TextBox("NomeDottore", Session["UserF"] as string, new { @class = "form-control", @readonly = "readonly" })
        </div>
    </div>
</div>
    <button type="submit" class="btn text-white mt-3" style="background-color:darkcyan">Paga Ora</button>
}

Views/Pharmacists/ProductsSearchXCodFisc.cshtml
@{
    ViewBag.Title = "ProductsSearchXCodFisc";
}

<h2>ProductsSearchXCodFisc</h2>

Views/Pharmacists/ProductsSearchXDate.cshtml
@{
    ViewBag.Title = "ProductsSearchXDate";
}

<h2>ProductsSearchXDate</h2>

Views/Pharmacists/Ricetta.cshtml
@model IEnumerable<ClinicaVeterinaria.Models.Examination>

@{
    ViewBag.Title = "Ricerca Ricetta";
}

<h2>@ViewBag.Title</h2>

@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">
        @TempData["ErrorMessage"]
    </div>
}

@using (Html.BeginForm("Ricetta", "Pharmacists", FormMethod.Post))
{
    <div class="form-group">
        <label for="MicrochipCodice">Codice Microchip:</label>
        <input type="text" class="form-control" id="MicrochipCodice" name="MicrochipCodice" placeholder="Inserire codice microchip">
    </div>
    <button type="submit" class="btn btn-primary mt-3">Cerca</button>
}

@if (Model != null && Model.Any())
{
    <h3>Patologie e Ricette:</h3>
    foreach (var item in Model)
    {
        <div class="card mb-3">
            <div class="card-header">
                Data Visita: @item.DataVisita.ToShortDateString()
            </div>
            <div class="card-body">
                <p>Patologie Riscontrate: @item.PatologieRiscontrate</p>
                <p>Ricetta: @item.Ricetta</p>
            </div>
        </div>
    }
}

Views/Pharmacists/_MedicineByDate.cshtml
@model IEnumerable<ClinicaVeterinaria.Models.Product>

@if (!Model.Any())
{
    <div class="mt-2">Nessuna medicina trovata per questa data.</div>
}
else
{
    <ul>
        @foreach (var item in Model)
        {
            <li class="fs-5 mt-3">@item.Nome</li>
        }
    </ul>
}

Views/Pharmacists/_ProdottiByCodiceFiscale.cshtml
@model IEnumerable<ClinicaVeterinaria.Models.Product>

<ul>
    @foreach (var prodotto in Model)
    {
        <li class="fs-5 mt-3">@prodotto.Nome</li>
    }
</ul>